# Esses dados você copia da página do seu projeto no SonarCloud
sonar.projectKey=wanesssatsantos
sonar.organization=wanesssatsantos

# Onde está o código do seu sistema que o E2E vai testar
sonar.sources=test

# Onde o Sonar vai procurar o arquivo de resultado dos testes
sonar.javascript.lcov.reportPaths=coverage/lcov.info