name: Pipeline de E2E com SonarCloud

on:
  push:
    branches: [ main, master ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: Rodar E2E e Enviar para o Sonar
    runs-on: ubuntu-latest
    steps:
      #Baixar o meu código com histórico completo
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        #instalção do node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x

      # Instalação do Yarn
      - name: Instalando Yarn
        run: npm install -g yarn
      # Instalaras dependências
      - name: Instalar dependências
        run: yarn 

    # instalação dos Browsers do Playwright
      - name: Instalando Browsers do Playwright
        run: yarn playwright install

      # Rodar os testes de E2E
      - name: Executar Testes E2E
        run: yarn run e2e

      # Enviar tudo para o SonarCloud analisar
      - name: Análise do SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    